### ISSUE TITLE
Feature: Retrieve candidate by email

### ISSUE THREAD

**Issue by acamilleri** [WTTJ/wk-api-docs#3]
Hello,

Can you add the possibility to retrieve candidate by email ?

ATM we need to retrieve list of all candidate and iterate on it to find the candidate with email "example@example.com".

**Comment by kle-roy** [comment]
Hi @krysennn, thanks for the feedback! 

Indeed, adding more available filters to `GET /api/v1/external/candidates` sounds like a good idea.

We will work on this in the next few weeks.

**Comment by acamilleri** [comment]
Hi @kle-roy,

Good, thank you very much ;)

**Comment by kle-roy** [comment]
hi @krysennn, 

sorry for the late answer, we added this feature few weeks ago: http://developers.welcomekit.co/#list-candidates

Also, FYI, we just released this morning some new endpoints: https://github.com/WTTJ/wk-api-docs/pull/5
